"""add phone number

Revision ID: 387d938ed9fe
Revises: f93840ea324f
Create Date: 2022-06-25 07:17:04.012680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387d938ed9fe'
down_revision = 'f93840ea324f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_numbers', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_numbers')
    # ### end Alembic commands ###
